version: '3.7'

services:
        dashboard:
                image: getumbrel/dashboard
                build:
                  context: ../umbrel-dashboard
                  dockerfile: Dockerfile.dev
                volumes:
                  - ../umbrel-dashboard:/app
        manager:
                image: getumbrel/manager
                build: ../umbrel-manager
                volumes:
                  # The following is required to correctly mount all services
                  # inside so they are accessible to docker-compose otherwise
                  # docker-in-docker fails becuase the compose file references
                  # build contexts that don't exist inside this container.
                  - ${PWD}/..:${PWD}/..
        middleware:
                image: getumbrel/middleware
                build: ../umbrel-middleware
