version: "3.8"

services:
  nginx:
    ports:
      # additional port for development
      - 8000:8000
  dashboard:
    image: runcitadel/dashboard
    build:
      context: ../dashboard
      target: development
    volumes:
      - ../dashboard:/app
    environment:
      DEVICE_HOSTNAME: ${DEVICE_HOSTNAME:-citadel-dev.local}
  ui:
    container_name: ui
    image: runcitadel/ui
    build:
      context: ../ui
      target: development
    volumes:
      - ../ui:/app
    env_file:
      - .env
    networks:
      default:
        ipv4_address: $DASHBOARD_NEW_IP
  manager:
    image: runcitadel/manager
    build:
      context: ../manager
      target: development
    volumes:
      - ../manager:/app
    command: sh -c "
      ./install-dependencies.sh &&
      ./start.sh"
      # TODO: watch mode does not yet work for manager
      # ./start-and-watch.sh"
  middleware:
    image: runcitadel/middleware
    build:
      context: ../middleware
      target: development
    volumes:
      - ../middleware:/app
    command: sh -c "
      ./install-dependencies.sh &&
      ./wait-for-manager.sh $MANAGER_IP &&
      ./start-and-watch.sh"
