version: "3.7"

services:
  dashboard:
    image: runcitadel/dashboard
    build:
      context: ../dashboard
      dockerfile: Dockerfile.dev
    volumes:
      - ../dashboard:/app
  manager:
    image: runcitadel/manager
    build: ../manager
    volumes:
      # The following is required to correctly mount all services
      # inside so they are accessible to docker-compose otherwise
      # docker-in-docker fails becuase the compose file references
      # build contexts that don't exist inside this container.
      - ${PWD}/..:${PWD}/..
  middleware:
    image: runcitadel/middleware
    build: ../middleware
